### ISSUE TITLE
MAC VERSION

### ISSUE THREAD

**Issue by OfficialJamestheFlames** [CrackThrough/ADOFAI-Mod-Installation-Guide#11]
PLEASE! make a mac version. please

**Comment by CrackThrough** [comment]
Old issue, but adofaigg dev team recently found a way to make modding possible through rosetta. i believe someone's going to write a guide on how to do that, but for now I'm putting this repository away and replace it with notion. Since no further real work will be done here, I'll close this issue. Stay tuned for rewritten guide!
